# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b80f0e57b3f048170e3b1e1cf9bb2a554b86560b7aeacf42bd76e64d42857d127444cbd4d1e74dd35068171d11590508d29ef4311b9e28e5c80eefa8ab8ce622

test:
  secret_key_base: 8201ca426420b01d5db31c73325e32a849082bad85f18f9a692b9611a9f394a1215f216173a5c2bf232f3a27ce9ef3354059aafa3ff81261fd62718d96dc357b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
